version: '2'
services:
    payara-full:
        build: mypayara-full
        ports:
            - "8080:8080"
            - "4848:4848"
        entrypoint:
            - /opt/payara5/bin/asadmin
            - start-domain
            - -v
        volumes:
            - ./data/payara:/opt/payara5/glassfish/domains/domain1/autodeploy
        depends_on:
            - db

    db:
        image: postgres
        ports:
          - "5432:5432"
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            PGDATA: /var/lib/postgresql/data/pgdata
        #volumes:
        #    - ./data/pgdata:/var/lib/postgresql/data/pgdata
