version: '2'
services:
    payara-full:
        image: payara-config:latest
        ports:
            - "8080:8080"
            - "4848:4848"
        depends_on:
            - db
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            POSTGRES_PORT: 5432
            POSTGRES_HOST: db
            POSTGRES_DATABASE: glassfish
            POSTGRES_POOL_NAME: postgres-pool
            APP_VERSION: 1.0.0-devMax-14
            APP_SHORT_NAME: project-room-rest
            PROJECT_DOWNLOAD_PATH: https://dl.bintray.com/maxrem/project-m2-room/fr/univtln/maxrem/projectroom
    db:
        image: postgres
        ports:
          - "5432:5432"
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            PGDATA: /var/lib/postgresql/data/pgdata
